### ISSUE TITLE
Farmer's Delight 0.4.2 and Some Assembly Required incopatibilities 

### ISSUE THREAD

**Issue by mk4000000** [ochotonida/some-assembly-required#16] opened 2021-05-07 18:22 UTC
I just noticed a recent update with "Farmer's Delight" (0.4.2) that "Cabbage Rolls now consult the tag farmersdelight:cabbage_roll_ingredients"

-It seems like with Some Assembly Required and Farmer's Delight installed it seems to throw an error when you have both.

- Unsure if this is something on your side with the compatiblity you have or on Farmer's Delights side.

**Comment by ochotonida** [comment] 2021-05-07 18:33
I can't reproduce this, can you give me a log/crash report?

**Comment by mk4000000** [comment] 2021-05-07 18:39
Yep lemme see what i can do

**Comment by mk4000000** [comment] 2021-05-07 18:54
versions that may be helpful:
-- Forge:  36.1.0 (but also tried up to 36.1.4 since that's the highest another mod seems to go i have before it has an issue. though if needed i can try a clean modpack with latest forge and just SAR and FD just to see if it still throws this error below)
-- someassemblyrequired-1.16.5-1.3.4.jar
-- FarmersDelight-1.16.5-0.4.2.jar
--- I tried this with Farmer's delight 0.4.1 and it seems to work fine so that's why im not sure if its something 'sar' is doing or Farmer's is doing with the tag change to the cabbage rolls.

First when trying to start a game with the most current version of Farmer's delight and Some Assembly required it fails to start open the save.

- subsequent starts give the issue 'Errors in the currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla datapack("safe mode", or go back to the title screen and fix it manually.

~~~~Error log below~~~~

[14:48:16] [Render thread/ERROR]: Couldn't load item tag farmersdelight:cabbage_roll_ingredients as it is missing following references: #forge:raw_pork (from FarmersDelight-1.16.5-0.4.2.jar)
[14:48:16] [Render thread/ERROR]: Couldn't load item tag forge:raw_pork as it is missing following references: minecraft:raw_porkchop (from someassemblyrequired-1.16.5-1.3.4.jar)
[14:48:16] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: minecraft:item:farmersdelight:cabbage_roll_ingredients
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[?:1.8.0_51]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1864) ~[?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) [?:?]
	at net.minecraft.client.Minecraft.lambda$loadWorld$25(Minecraft.java:1720) [?:?]
	at net.minecraft.client.Minecraft$$Lambda$20173/2066421372.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.DatapackFailureScreen.func_238622_b_(SourceFile:23) [?:?]
	at net.minecraft.client.gui.screen.DatapackFailureScreen$$Lambda$20174/814736773.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$16315/533123465.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$16314/1702759896.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$13503/853166047.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) [lwjgl-glfw-3.2.2.jar:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:99) [?:mc1.16.5-1.19]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) [?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/966745519.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
Caused by: java.lang.IllegalStateException: Missing required tags: minecraft:item:farmersdelight:cabbage_roll_ingredients
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:47) ~[?:?]
	at net.minecraft.tags.NetworkTagManager$$Lambda$17392/1600952154.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$13751/848749616.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) ~[?:?]

**Comment by mk4000000** [comment] 2021-05-07 19:15
OK so i just made a fresh pack with just JEI, Some assembly Required and Farmer's Delight
- Farmer's Delight 0.4.2 and Some Assembly Required 1.3.4
-- This time it did not crash with jsut these few mods, however when i checked the Cabbage Roll recipe it did not exist.

- Thinking maybe it is a Farmer's Delight side error i tried running it withouth SOme assembly Required
- -- without SAR the Cabbage roll has its proper cook pot recipe.

Im thinking its possibly something that got changed on Farmer's Delights end now. When it looks through the recipe and tries to tag ingtedients for the cabbage roll it seems Some assembly Requireds port and throws a fit.  Not sure why though. I could submit this error to them too to see if they can figure it out?

**Comment by ochotonida** [comment] 2021-05-07 19:19
It's definitely an issue on my end, I'll get it fixed once I find the time

**Comment by mk4000000** [comment] 2021-05-07 19:26
Thank's for the help. Awesome mod btw. and i appreciate all the integrations

**Comment by ochotonida** [comment] 2021-05-09 10:05
Should be fixed in the latest release

**Closed as completed by ochotonida** 2021-05-09 10:05 UTC
