### ISSUE TITLE
Food doesn't update right.

### ISSUE THREAD

**Issue by TheSpicePhantom** [ochotonida/some-assembly-required#17] opened 2021-06-13 09:00 UTC
Sometimes when a sandwich is being eaten, it doesn't update hunger correctly.
I've just eaten 5 sandwiches, took damage and the hunger was back to where it was before.

**Comment by Dimitry-Blitzbrieg** [comment] 2022-01-02 02:07
I'm having the same issue. playing version 1.15.2, I eat baked potato and steak sammich and it fails to update hunger... this happens on any sammich style i make. even items from other mods.

**Comment by Dimitry-Blitzbrieg** [comment] 2022-01-02 02:08
i mean 1.16.5 oops

**Comment by ochotonida** [comment] 2022-01-02 11:39
Can you give me a list of the mods you have installed? I can't reproduce this issue with just Some Assembly Required, so there's probably another mod involved. Also, are you playing singleplayer or on a server?

**Comment by ochotonida** [comment] 2022-03-01 10:27
I'm going to close this issue as I don't have enough information to resolve it, feel free to open a new issue with more information if you're still having this problem. (Due to major design changes, this likely isn't an issue in 1.18 anymore)

**Closed as completed by ochotonida** 2022-03-01 10:27 UTC

**Comment by BrawleyGithub** [comment] 2024-05-24 21:15
Hey so, I know I'm really late but I figured out why this is happening. Stacking sandwiches doesn't work properly, the first sandwich gives proper nutrition but as long as it remains in the same hotbar slot any other stacked sandwiches don't register their values properly. Happens in a test pack with only SAR and JEI. Probably won't get fixed this late but if anyone else is in the 1.16 version either don't stack sandwiches or make sure to move the stack after each sandwich.

**Comment by ochotonida** [comment] 2024-05-26 20:00
Thanks for the extra info, this finally allowed me to reproduce the issue myself. I've uploaded a patch that fixes it.
