### ISSUE TITLE
Tomato/Onion Slices unobtained via cutting board

### ISSUE THREAD

**Issue by Ethanthelandlord92** [ochotonida/some-assembly-required#40] opened 2023-08-10 00:57 UTC
When I cut tomatoes/onions using the cutting board, I don't get anything forcing me to resort to using the mechanical saw.

**Comment by ochotonida** [comment] 2023-08-10 09:22
What version of Some Assembly Required and Farmer's Delight are you using? A log file might also help

**Comment by Ethanthelandlord92** [comment] 2023-08-10 12:55
I'm using game version 1.20.1

**Comment by ochotonida** [comment] 2023-08-10 13:51
I can't reproduce this with just Some Assembly Required and Farmer's Delight, so it could be caused by another mod you have.
What exactly happens when you try to cut an onion/tomato? Does nothing happen at all or does it delete the item? It would also be useful to know if it happens to any other items, like bread or items from Farmer's Delight.
Can you give me a log file of a session where you tried to cut an onion/tomato?

**Comment by Ethanthelandlord92** [comment] 2023-08-10 14:00
Whenever I cut an onion/tomato, it deletes the item. Bread, beetroot, and carrots are unaffected by this. I've been looking into the log files and I couldn't find the log file.

**Comment by Ethanthelandlord92** [comment] 2023-08-10 14:24
I think I found the problem with this, there might be another mod conflicting with the mod I currently have installed.

**Comment by ochotonida** [comment] 2023-08-10 14:59
Log files are usually placed in the `logs` folder in your install directory.
Let me know if you figure out what mod is causing it, might be useful to know in case it's something that can be fixed on my side.

**Comment by ochotonida** [comment] 2023-08-17 11:50
I'm assuming you managed to fix this problem by now, would be nice to know what was causing it though. Could help with preventing similar issues in the future.

**Closed as not planned by ochotonida** 2023-08-17 11:50 UTC
